workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      vars:
        IPHONEOS_DEPLOYMENT_TARGET: 14.0
    scripts:
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app