workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      vars:
        IPHONEOS_DEPLOYMENT_TARGET: 14.0
    scripts:
      - name: Build iOS
        scripts:
          - cd portal_investidor-main
          - flutter build ios --release --no-codesign
    artifacts:
      - portal_investidor-main/build/ios/iphoneos/*.app